### ISSUE TITLE
Horizontal scrollbars appearing when there is nothing to scroll.

### ISSUE THREAD

**Issue by stephen-slm** [HiDeoo/YaTA#10]
**Describe the bug**

Scrollbar appears when the window is at the minimal size when there is no reason for it to exist.

**To Reproduce**

Using the windows snap feature, snap two windows side by side and drag the window containing YaTa as small as possible, scroll bar will appear at the bottom of the page, scrolling to nothing.

**Expected behavior**

No scroll bar.

**Screenshots**

![image](https://user-images.githubusercontent.com/12329422/48761376-62203300-eca0-11e8-988c-12f7b337bcc2.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.7.0
| Browser          | Chrome 70.0.3538.110
| Operating System | Windows NT 10.0

**Comment by stephen-slm** [comment]
Additional Notes:
- The channel title seems to be pushing the UI Navigation off the page which in turn creates the scrollbars only when its just short enough not to be wrapped (roughly 70 characters).

**Comment by HiDeoo** [comment]
This is now fixed and will be available in the next version when released.
