### ISSUE TITLE
Optional notification sound on every chat message, or visual indicator of new messages

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#11]
**Is your feature request related to a problem? Please describe.**

This is not a problem with YaTa, but a suggestion to help make it more useful for me.  I'm not a very observant streamer, and I often miss chat messages if I'm concentrating on something.  So I use a Twitch chat program that lets me configure a short sound to be played on every chat message.  This helps grab my attention so that I interact with the community and they don't feel ignored.  YaTa doesn't have this feature, so it's not optimal for me to use it while streaming.

**Describe the solution you'd like**

Under Settings -> Notifications -> Sound, you can enable playing a sound on mentions and whispers.  It would be nice if there was another option, to play sound on all messages.

**Describe alternatives you've considered**

I use another Twitch chat client (chatty) which has this feature, and it helps me out most of the time (sometimes I still miss messages).  Alternatively, if YaTa could have some visual indicator that there are "unacknowledged messages", that might work as well.  For example, in Discord there is a red line and text that says "NEW MESSAGES" on any messages that came in since you last clicked on or visited a channel.  It's not too intrusive, yet if you look for it, it can help divide chat messages already "seen" versus new ones I may not have noticed appear recently.

**Additional context**

Here is what the visual indicator in Discord looks like:
![image](https://user-images.githubusercontent.com/41497796/49044985-4fb46680-f184-11e8-968c-6bcce08947ca.png)

**Comment by rhymu8354** [comment]
Additional notes:

If YaTa were to have a visual indicator like Discord, it need not show up if YaTa already has the focus, because most likely if it is has the focus, I'm actively looking at it.  Also, the indicator could be easy to dismiss, like simply clicking into the text entry box at the bottom.

Also I admit this feature is mostly useful for new / small streamers with "slow" chat.  Perhaps YaTa could automatically disable or "suspend" the feature if chat frequency passes a certain threshold.  For example, if I'm suddenly raided by 30 people and there's a lot of chat, chances are the "new messages" indicator or sound will cease to be of use.

**Comment by HiDeoo** [comment]
Here are the sound changes that I made hoping it'll fit your needs:

- New notification sound for messages (disabled by default).
- Individual volume configuration for each sound
- Message sounds can be limited to your own channel via a setting
- A minimum delay between each sound notification for messages can be configured.

Regarding the visual one, I didn't change anything so far as I still haven't thought of something that would fit the application but I'm keeping this on my radar.
