### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by mercxry** [HiDeoo/YaTA#12]
**Is your feature request related to a problem? Please describe.**

I would like to have a dedicated application for Twitch chat so I can let the chat run in background and get a notification when someone mentions me

**Describe the solution you'd like**

A desktop application maybe done with Electron so it can easily support all PC platforms and would be easier to integrate with React

**Describe alternatives you've considered**

A simple desktop application with a web view but that's not really good to see 

**Additional context**

The desktop application should be able to notify on mentions using the OS notification system (should be easier with electron)

**Comment by HiDeoo** [comment]
Thanks for you feedback, as a matter of fact, I'm kinda in the same boat and would love a dedicated application.

Having worked a lot with Electron, I'm kinda against publishing a 140MB+ package for something that shouldn't be more than 5MB at most. And top of that, this would be nothing more than a glorified webview with an icon and not a lot of *native* features (I think notifications may be the only one actually ^^).

The good thing is, we may be *relatively* close to the end of Electron (I like the tech & idea, don't get me wrong, it's just silly tho to bundle Chromium as a library in each Electron app) thanks to a new project from GoogleChromeLabs named [carlo](https://github.com/GoogleChromeLabs/carlo).

What carlo does is basically checking if you have Chrome installed locally and if you do, it'll communicate with the locally-installed Chrome instance using [Puppeteer](https://github.com/GoogleChrome/puppeteer/) for everything related to rendering for a size of just 2MB.

I've already started experimenting with it in a local branch, I have a very basic hacky version running, but carlo is very new, there is still a lot missing so it'll take time but if there is ever an application, it'll be using carlo or something different of Electron.

I'm closing this issue for now as it's already in my radar and something I want but won't be released very soon.

PS: good luck on Notify ^^
