### ISSUE TITLE
Multiple chat tabs

### ISSUE THREAD

**Issue by mercxry** [HiDeoo/YaTA#13]
**Is your feature request related to a problem? Please describe.**

I moderate multiple chats so I need to check multiple chats and opening more tabs in the browser takes too much space

**Describe the solution you'd like**

I would like to have multiple chat tabs within the app, without opening a new tab on the browser

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by HiDeoo** [comment]
This feature is part of the features I already want to implement in a future desktop application and only in a desktop version as I'd like to implement some advanced features for it like detaching a tab to a new window, grouping multiple windows in a single one with tabs, use your native os window management, etc. (this should land in cargo at some point).

So when #12 is released, this feature will be part of it.
