### ISSUE TITLE
Scroll bar locks up when you select all chat messages and attempt to scroll

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#15]
**Describe the bug**

I noticed that when there are a lot of messages (many times the visible vertical height of the window), the scroll bar will refuse to scroll very far, and will "lock up", if before I scroll I select all chat messages.

This is somewhat related to issue #14 perhaps. (?)

**To Reproduce**

1. Go into any channel.
2. Wait until enough chat messages have been received that they span many "pages" (many times the visible vertical height of the window).
3. Click anywhere in the chat log.
4. Press Ctrl+A.
5. Click and drag the scroll bar and attempt to scroll up or down some distance (a distance of perhaps 3 or more messages)
6. Observe that the scroll bar appears to "lock up", the mouse cursor is replaced with a circle with a slash through it, and you cannot scroll anymore unless you first release the mouse and click and drag the scroll bar again.

**Expected behavior**

I expect the window to keep scrolling and allowing me to scroll anywhere in the chat history.

**Screenshots**

It's difficult to show in screenshots because I can't figure out how to include the mouse cursor in the screenshot, so I decided to record with OBS and convert to GIF:
![yata-issue-15](https://user-images.githubusercontent.com/41497796/49123764-a4341080-f26e-11e8-9068-55813982b19d.gif)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.7.0
| Browser          | Firefox 63.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
This seems to be a Firefox issue as I can only repro something similar in this browser.

After some investigations, there are indeed bug reports about this exact issue altho, the [main one](https://bugzilla.mozilla.org/show_bug.cgi?id=491079) was opened 10 years ago, last updated 3 years and still not fixed so…

As this is related to #14, I'll address this one specifically somehow so you should never have to select everything & drag the scrollbar.

**Comment by HiDeoo** [comment]
Side note: thanks the amazing bug report and taking the time to spin up OBS to record it 👍
