### ISSUE TITLE
Ability to see all channels, abilitiy to send whispers without joining a channel and ability to hide the top bar

### ISSUE THREAD

**Issue by ifohancroft** [HiDeoo/YaTA#16]
If you'd like me to make separate feature requests for each of the features I am requesting - let me know. I decided to include them all into one report so I am not spamming.

1. I have just realised that you can only see and search amongst the channels I am following. I believe we should be able to see and search all channels. I use Twitch's website chat when I am watching a stream. My reason for using YaTA is so I can look at my own chat during stream, so being able to only search for a channel I am following, isn't working for me (even though I can get into any channel I want by typing it into the URL).

2. Since YaTA supports whispers, it doesn't make sense that I need to enter a channel, in-order to be able to send a whisper.

3. I'd love a shortcut to hide the top bar (the one with the streamer's name, settings button, etc). State (hidden or visible) should be remembered even if I close YaTA's website or logout.

**Comment by HiDeoo** [comment]
No problem, 1 issue is totally fine, thanks for your feedback :)

1. This was part of my original plan to provide more *"discovery"* feature, some ways to explore Twitch altho, Twitch APIs regarding this case are just close to void and I don't want to only provide an infinite list of top streams. If I ever revisit this idea, it'll be when Twitch provides proper APIs for that aka, per game, per tags, searching, etc.

2. This is planned for a future desktop application of YaTA if it ever happen, not in the web version, where you'll have multiple channels support through tabs & windows and whispers will get their own tab / window available at any time. 

3. I'm ok with that.

I'll close this issue when I'll have implemented your third point.

**Comment by HiDeoo** [comment]
Point 3 will be available in the next version (no ETA yet).

**Comment by ifohancroft** [comment]
I hope this comment doesn't reopen the issue. Sorry if it does.

1. Yeah. Twitch's API is not one of the best and consistent ones. Maybe a quick button/shortcut + maybe setting to go to your own vhannel and the setting will be to open your own channel on open. My reason for asking this is because I use a bash script that starts the software I need gor streamimg and rearranges it for me on the second monitor (using wmctrl) and I try to avoid having to manually do any of those stuff.

2. Nice!

3. Awesome! Thank you!

**Comment by HiDeoo** [comment]
Yeah, I kinda have the same process, everything to open chats is scripted, window position, which screen, etc. and all of this is plugged into some Alfred workflows so I can quickly open my channel, other channels, etc. altho I only rely on URL which is imo what you would expect from a web app.

Altho, on top of that & the already existing omnibar that you can use to switch between channels, I added a new shortcut to directly navigate to your own channel.

**Comment by ifohancroft** [comment]
Thanks and I keep forgetting about the url. I can use that as well, indeed.
