### ISSUE TITLE
YaTa does not display #charity messages

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#18]
**Is your feature request related to a problem? Please describe.**

I noticed that the special #charity cheer messages don't show the Twitch charity announcement message in YaTa like they do in built-in Twitch chat.

**Describe the solution you'd like**

It would be nice if YaTa displayed the same content (charity link, etc.) as the built-in Twitch chat.

**Describe alternatives you've considered**

Built-in Twitch chat? ;)

**Additional context**

I captured the raw chat message using my Lurker program as well as screen-shots from both YaTa and the built-in Twitch chat.

Raw message:  `@badges=;color=#8A2BE2;display-name=Twitch;emotes=;flags=;id=61f9f765-97be-42e7-9d53-1ce8f21d0910;login=twitch;mod=0;msg-id=charity;msg-param-charity-days-remaining=15;msg-param-charity-hashtag=#charity;msg-param-charity-hours-remaining=366;msg-param-charity-learn-more=https://link.twitch.tv/blizzardofbits;msg-param-charity-name=Direct\sRelief;msg-param-total=22557;room-id=92967549;subscriber=0;system-msg=$22,557\stotal\sraised\sso\sfar\sfor\sDirect\sRelief!\s15\smore\sdays\sto\sshow\ssupport.\sCheer\sand\sinclude\s#charity.\sLearn\sMore\sat\shttps://link.twitch.tv/blizzardofbits;tmi-sent-ts=1544665731953;turbo=0;user-id=12826;user-type= :tmi.twitch.tv USERNOTICE #ygtskedog`

Message as it appears in built-in Twitch chat:
![image](https://user-images.githubusercontent.com/41497796/49910440-97e7b000-fe37-11e8-8420-eb5fe2cdedf1.png)

Same message, in context (dark theme applied):
![image](https://user-images.githubusercontent.com/41497796/49910464-a7ff8f80-fe37-11e8-90ed-7467f05928e4.png)

Lack of message in YaTa:
![image](https://user-images.githubusercontent.com/41497796/49910470-af269d80-fe37-11e8-9e77-b0afbde1e045.png)

**Comment by rhymu8354** [comment]
Sorry for the non-family-friendly text in the screen-shots.  I wasn't paying much attention to the actual words said at the time I was trying to capture the datas.

**Comment by HiDeoo** [comment]
This is now supported in `v1.8.2` which has just been released.

<img width="795" alt="screenshot 2018-12-13 at 13 17 41" src="https://user-images.githubusercontent.com/494699/49942298-3a11a180-fee5-11e8-8c4f-918967accec9.png">
