### ISSUE TITLE
Erratic scroll bar behavior

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#19]
**Describe the bug**

When I click and drag the scroll bar, the "thumb" or scroll position indicator sometimes jumps around, especially when scrolling a longer distance.

This may or may not be a problem with YaTa.  It might also be in react-virtualized or even just something that the browser does (in this case I used Firefox).  Feel free to close this if you want.

**To Reproduce**

1. Go to a large channel (e.g. Kitboga)
2. Allow many messages to accumulate.
3. Left-click and drag the scroll bar thumb up/down large distances.
4. The scroll bar thumb appears to "jump" to slightly wrong positions.  It snaps back to the cursor position each time the mouse is moved.

**Expected behavior**

Optimally, the scroll bar thumb should track the mouse vertical position relative to the mouse movement since the drag began.

**Screenshots**

![yata-scrolling](https://user-images.githubusercontent.com/41497796/49978322-c67c8e00-fefe-11e8-84b2-1386bf7fd67d.gif)

**Environment (please complete the following information)**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.8.2
| Browser          | Firefox 63.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
The current behaviour is expected as this is simply me purging some old chat messages so the offset actually changes for the thumb.

I could prevent this issue very easily by not purging while scrolling altho this could potentially lead to some other issues. If someone for w/e reasons do something kinda like what you did in the capture and end up scrolling for a large amount of time (looking for something for example) in a very fast chat, the amount of messages could potentially accumulate very fast and that's something I originally want to prevent.

I guess one potential workaround could be to have 2 hard limits for purging messages, one used most of the time and one slightly higher used when the user is scrolling.

Another option, as YaTA is performing pretty decently, I could increase the current limits a bit to not purge so often as the number are currently pretty low.

On the other end, I don't think it's something a lot of users tend to do, so I'll keep an eye on this and if this comes up again in another issue, I'll implement one or all the solutions I suggested above.

*Note: the text disappearing is a Firefox issue ^^*
