### ISSUE TITLE
Disable up arrow when text is entered

### ISSUE THREAD

**Issue by tollus** [HiDeoo/YaTA#2]
**Describe the bug**
When typing a longer message if you click the up-arrow you lose the entire message. I think this is very similar in the twitch client, they may remember your message, I don't recall.

**To Reproduce**

1. Type something in the chat box that makes it wrap at least 1 time.
2. At the end of the line, press the up arrow to "fix" a typo in the first line.
3. See the last message you typed out in chat.

**Expected behavior**

I would just expect the up arrow to go the previous line, and not pull the last message from chat history.

**Screenshots**

Let me know if you want this.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 0.5.0
| Browser          | Chrome 67.0.3396.99
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
My short-term plan regarding this issue was actually instead of disabling the up arrow to add a concept of "draft" aka saving the current input and restoring it back when coming back using the down key.

What do you think of this solution?

**Comment by tollus** [comment]
yeah, that works too
