### ISSUE TITLE
text overlapping issue

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#20]
It looks like for some messages there is an overlapping issue at times.  See screen-shot.  I don't know if it's a Firefox issue or a YaTa issue.  It may be a coincidence that the two overlaps I saw were when messages ended in links.

**Screenshots**

![image](https://user-images.githubusercontent.com/41497796/50575278-d5918600-0db0-11e9-9cae-f0ae1f602996.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.8.2
| Browser          | Firefox 64.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Yeah, this is an old bug still tracked on my end that I can only reproduce in Firefox in Windows altho so far the poor workarounds for the issue is not something I want to add to the codebase. Maybe I'll re-evaluate in 10 years when FF decides to change this 😄
