### ISSUE TITLE
Sub streak notification shows "0 months in a row"

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#21]
**Describe the bug**

Re-subscription notices show "0 months in a row"

**To Reproduce**

1. Go to a channel where the normal Twitch UI shows you can share your anniversary.
2. Make sure YaTa is also in the same channel's chat.
3. Share anniversary in normal Twitch UI.

**Expected behavior**

Announcement should say the correct number of months in a row.

**Screenshots**

![image](https://user-images.githubusercontent.com/41497796/52242097-74b30d00-288a-11e9-8dc3-dc43edc33f3a.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.8.2
| Browser          | Firefox 65.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
Yeah, saw that, I can't investigate right now, I'm not even sure if it's a change in what they're throwing at us with their new broken feature, if it's the huge issue they had when releasing the feature that [they're still recovering from](https://twitter.com/TwitchSupport/status/1092530831128616960), or something else.

Also, if I can somehow identify these useless notifications from real re-subs, I may totally remove them ^^ That's useless spam

**Comment by rhymu8354** [comment]
I collected a raw message if it might help some:

`@badges=subscriber/12,bits/1000;color=;display-name=thebirdabides;emotes=;flags=;id=bc474d4d-7524-428a-9e24-6df2cd0b4d8c;login=thebirdabides;mod=0;msg-id=resub;msg-param-cumulative-months=12;msg-param-cumulative-tenure-months=12;msg-param-months=0;msg-param-should-share-streak-tenure=true;msg-param-should-share-streak=1;msg-param-streak-months=12;msg-param-streak-tenure-months=12;msg-param-sub-plan-name=Each\sAnd\sEverything\sPlan;msg-param-sub-plan=1000;room-id=32787655;subscriber=1;system-msg=thebirdabides\sSubscribed\sat\sTier\s1.\sThey've\ssubscribed\sfor\s12\smonths,\scurrently\son\sa\s12\smonth\sstreak!;tmi-sent-ts=1549325994471;turbo=0;user-id=48686970;user-type= :tmi.twitch.tv USERNOTICE #kitboga`

It looks like the usual parameter `msg-param-months` is `0`, and instead there are two pairs of new parameters: `msg-param-cumulative-months`, `msg-param-cumulative-tenure-months`, `msg-param-streak-months`, and `msg-param-streak-tenure-months`.

There is also a pair of flags, `msg-param-should-share-streak-tenure` and `msg-param-should-share-streak` to indicate whether or not the user marked that they wanted their streak to be shared.  Interestingly, one is true/false while the other is 1/0.

**Comment by HiDeoo** [comment]
Turns out, `msg-param-streak-tenure-months`, `msg-param-cumulative-tenure-months` & `msg-param-should-share-streak-tenure` are already deprecated, yes, they manage to just release already deprecated stuff. Types are also wrong on their end (they know about this) but this should now be fixed.

<img width="603" alt="screenshot 2019-02-05 at 09 56 56" src="https://user-images.githubusercontent.com/494699/52262458-d330c780-292c-11e9-84fb-0fa6824a36f9.png">

<img width="481" alt="screenshot 2019-02-05 at 09 57 11" src="https://user-images.githubusercontent.com/494699/52262468-d5932180-292c-11e9-8689-034a687bd67a.png">
