### ISSUE TITLE
Cant sign in

### ISSUE THREAD

**Issue by dualznz** [HiDeoo/YaTA#22]
**Describe the bug**
After creating and building the app, i edited the .env file and added in my client ID and redirect uri to http://192.168.1.203:3000 and i see this error when trying to login with twitch...

{"status":400,"message":"Sorry, the scope you are requesting is currently unavailable. Please request new scopes documented at https://dev.twitch.tv/docs/authentication/#chat-and-pubsub."}

There is no documentation on how to get this going locally which makes it borderline impossible for new users.

I also went to twitch developer site and generated a client key and set the redirect endpoint to http://192.168.1.203:3000

Furthermore i have tried http://localhost with / without port 3000 and still not working, some help would be appreciated.

**To Reproduce**

**Expected behavior**

should let me sign in so i can use this app locally

**Environment (please complete the following information)**

| Software         | Version
| ---------------- | -------
| YaTA             | latest on github
| Browser          | chrome
| Operating System | on ubuntu 16.04-2 server

**Comment by HiDeoo** [comment]
Yeah, the `README` is not great and I don't have the time right now to expand on it unfortunately (added that to my todos tho as it's an important improvement) but depending on your usage, the hosted version may be enough.

If you still need to run locally, I would advise to create your own `.env.development.local` which would looks something like this (notice the `/auth`  at the end of the redirect URI):

```
REACT_APP_VERSION=$npm_package_version
REACT_APP_BUGS_URL=$npm_package_bugs_url

REACT_APP_TWITCH_CLIENT_ID=your_twitch_app_client_id
REACT_APP_TWITCH_REDIRECT_URI=http://localhost:3000/auth

REACT_APP_YOUTUBE_API_KEY=your_youtube_api_key

REACT_APP_IMGUR_CLIENT_ID=your_imgur_api_key
```

**Comment by dualznz** [comment]
Thanks for the quick reply, I followed your steps and also updated the twitch dev to return to the auth url but it is still doing the exact same thing, I'm stumped

**Comment by HiDeoo** [comment]
I tried to logout / login again on my local dev version for sanity but it works. That's weird.

What's the exact error / issue? 

In your app, your `OAuth Redirect URL` is also `http://localhost:3000/auth` right? Altho, it would just be a 404 so I guess that's not related.
The Client ID is also the one of an *App* right?

I guess there is something missing / wrong but can't pinpoint what, and I know some people run a local version so I guess it might just be a very small thing.

**Comment by dualznz** [comment]
ok so if i was to bind it to say yata.domain.com/auth then it should in theory work, using just the .env and also once built and served change the domain in package.json ? cause i would really like for this to work

The exact issue is the one i provided, i created a .env.development.local added the required information including http://localhost:3000/auth on both twitch return uri and in the file   also just using .env also

when i click on "sighin with twitch" i get 
{"status":400,"message":"Sorry, the scope you are requesting is currently unavailable. Please request new scopes documented at [https://dev.twitch.tv/docs/authentication/#chat-and-pubsub."}](https://dev.twitch.tv/docs/authentication/#chat-and-pubsub.%22%7D)

and cannot login or proceed past that error at all

**Comment by HiDeoo** [comment]
Yeah it should, I personally have a `.env.development.local` file bound to `http://localhost:3000/auth` and a `.env.production` used only in prod bound to `https://yata.now.sh/auth`.

Altho, considering the error you're getting is coming from Twitch, I would say it's not even trying to hit your auth URI. Not sure if the *currently* in their error mean something, like is this temporary? I thought it could be related to the client-id you're using not being the one of an app like I said in my previous answer but if not, I'm out of idea.

**Comment by HiDeoo** [comment]
Actually just typing your error in the Twitch dev forums returns [this post](https://discuss.dev.twitch.tv/t/the-scope-you-are-requesting-is-currently-unavailable/17038/9), it might be your problem. I quickly read through it, looks like the solution would either to be whitelisted (no idea for what) or change the scope the application is using.

Maybe new applications only have an issue due to: 

> You could try the new chat:read, chat:edit, and channel:moderate scopes since it looks like those don’t need to be whitelisted. They were recently introduced after chat_login started being abused but have not been added to the documentation yet.

**Comment by dualznz** [comment]
ok so i have removed the project and am redoing it from scratch using my real domain and have made sure  to update twitch to yata.domain.com/auth and using the ClientID: that was generated by the application generator. will see if this works if not thats a pitty.

**Comment by dualznz** [comment]
oh ill try and generate a key that way

**Comment by HiDeoo** [comment]
Did you check the previous link I posted and investigate around that?

**Comment by dualznz** [comment]
ehh nope {"status":400,"message":"invalid client"} with and without oauth: in front 
bahhhhh

**Comment by dualznz** [comment]
i mean there is nothing on my end that should be stopping this, i use twitch dev for other apps i have built and havnt ran into this, its like the scopes that is being requested when logging in is not valid but thats controlled via your code.

so i have no idea and i want to run this on my ipad mini for when im streaming but hmmmm 
also no token is being returned in the url is that normal ? im also using client ID and not client secret in .env and .env.production

**Comment by HiDeoo** [comment]
Yeah, like it's explained in the post above, you may need to get whitelisted to get the scopes or use some new scopes as I don't have the time right now to refactor this as I don't have this issue (if that's even the issue).

Also, if you don't mind me asking, if the idea is to use it on your iPad mini while streaming, why don't you use the hosted version?
