### ISSUE TITLE
Strange interaction with dark mode extension

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#23]
Preface: This is probably not a bug in YaTA, but rather an unexpected side-effect or sensitivity in YaTA to a FireFox add-on that I use (see below).  So no need to "fix" anything, unless you want to of course. :)

When using FireFox with the [dark-background-light-text-extension](https://github.com/m-khvoinitsky/dark-background-light-text-extension) add-on, if I enable it, all the colors of chatters change to white.  At first I thought this was a bug in YaTA, but after my stream ended and I turned off the dark mode, saw YaTA had an issue, then refreshed it, it was back to working again.

**To Reproduce**

1. Go to any twitch stream in YaTA, in FireFox with the [dark-background-light-text-extension](https://github.com/m-khvoinitsky/dark-background-light-text-extension) add-on installed but not enabled.
2. Wait for some chat messages to be sent in channel, with chatters' names that aren't white.
3. Enable the [dark-background-light-text-extension](https://github.com/m-khvoinitsky/dark-background-light-text-extension) add-on (see screen-shot below to see exactly how I enable/disable it).
4. Observe all chatters' names are now white.
5. Turn the [dark-background-light-text-extension](https://github.com/m-khvoinitsky/dark-background-light-text-extension) add-on off again (same checkbox, just turn it off)
6. YaTA either shows a generic "something bad happened" error or it shows just a random emote in the top-left corner.  Reloading YaTA at this point fixes it.

**Expected behavior**

I expected YaTA to either be unaffected by the add-on or for its color scheme to adapt according to the expected behavior of the add-on.

**Screenshots**

Before enabling the extension:
![image](https://user-images.githubusercontent.com/41497796/54166644-60cb6f80-4423-11e9-83c5-8c5ede6e60a3.png)

Control to enable the extension:
![image](https://user-images.githubusercontent.com/41497796/54166760-ed762d80-4423-11e9-9f56-b963fc874334.png)

After enabling the extension:
![image](https://user-images.githubusercontent.com/41497796/54166652-6de85e80-4423-11e9-98df-d733b2cb03c5.png)

Then disabling the extension again:
![image](https://user-images.githubusercontent.com/41497796/54166659-78a2f380-4423-11e9-891d-e0810de47f7d.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.8.3
| Browser          | Firefox 65.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
This is a conspiracy to make me open Firefox, right? 😆

So I checked in the same version of Firefox after installing the extension, tested in multiple chats (spammed, not spammed, etc.) and I can't repro. I get the all white text part after enabling the extension using the menu you showed altho disabling it doesn't cause any error on my end 🤔

I can think of 2 possibilities:

- In the extension menu, you seems to select a profile or something for `twitch.tv`, I don't have this, I mean I don't have a specific thing for Twitch. I assume you added that yourself somehow? Could this be related? Is this something you could share?
- It's a combination of extensions leading to the error.

**Comment by HiDeoo** [comment]
Closing this for now due to lack of follow-up, feel free to re-open if you want.
