### ISSUE TITLE
Whispers sent from YaTA appear to be broken

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#26]
**Describe the bug**

Whispers sent from YaTA do not appear to make it to the recipient, whereas whispers sent from the built-in twitch chat do make it through.

**To Reproduce**

1. Go to any twitch channel in both YaTA and built-in Twitch chat.
2. Send a whisper from YaTA:  "/w PlayingWithSkissors Hello from YaTA"
3. Send another whisper from built-in Twitch chat:  "/w PlayingWithSkissors Hello from Twitch chat"
4. Confirm with recipient that they only received the second whisper, not the first one.

**Expected behavior**

The recipient should receive both whispers.

**Screenshots**

![image](https://user-images.githubusercontent.com/41497796/57470663-3983f980-723e-11e9-842a-7952844b0bce.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.8.3
| Browser          | Firefox 66.0
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
I can't seem to repro when either sending/receiving with YaTA.

Are you still able to repro? Could it have been a temporary Twitch issue? Is there any more repro steps I could be missing?

Closing this for now, feel free to re-open and comment if it's still an issue for you.

**Comment by rhymu8354** [comment]
Seems to be working now; I guess it was something temporary on Twitch end.  🤷‍♂
