### ISSUE TITLE
VIP-Badge

### ISSUE THREAD

**Issue by klaraso** [HiDeoo/YaTA#27]
**Describe the bug**

You cant see the VIP-Badge in YaTA

**Expected behavior**

It should show you the VIP-Badge like any other Badge, but it dont shows.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.9.0
| Browser          | Chrome 74.0.3729.157
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment]
You can enable them in all channels through the general settings:

<img width="455" alt="Screenshot 2019-05-22 at 14 26 19" src="https://user-images.githubusercontent.com/494699/58174594-89cb7480-7c9e-11e9-894a-c47041b2c7df.png">
