### ISSUE TITLE
'RIGHT-TO-LEFT OVERRIDE' (U+202E) not displayed properly

### ISSUE THREAD

**Issue by Neui** [HiDeoo/YaTA#28]
### Describe the bug

It seems that YaTA strips/does not render the unicode character 'RIGHT-TO-LEFT OVERRIDE' (U+202E) correctly.

### To Reproduce

On Twitch vanilla chat:

1. Insert `!pts rhymu8354 99999` into the chatbox
2. Position the cursor before the first number (between the `u` and `8`)
3. Insert the unicode character U+202E
   * On at least Ubuntu Firefox, you can hold down CTRL+Shift, then type `u202e`, then let go of CTRL+Shift
   * Assuming GitHub doesn't mangle, it should then look like this: `!pts rhymu‮8354 99999`
4. Send

### Expected behavior

Display the message as:

> !pts rhymu‮8354 99999

### Actual behavior

The message is being displayed as:

> !pts rhymu8354 99999

![Image demonstrating the output difference](https://i.imgur.com/zAUXaxW.png)

The right one is the vanilla twitch chat, the left one is the streamers chat, which claims to use YaTA. [See it in the VOD: 0192, 3h53m42s](https://www.twitch.tv/videos/431147580?comment=658cffff-e99c-43e4-bf13-82bc7a94e2f5&t=03h53m42s). Note that in the chat-replay, it seems it is also displayed incorrectly, but it did display like in the screenshot when I sent it. (Maybe it was displayed like that just on my end?)

### Environment

I am on Ubuntu 18.04 with Firefox 67.0 (64-bit), using Twitch vanilla chat. Try asking @rhymu8354 for their information. I guess at least Windows 10 on Chrome.

**Note**: I don't use YaTA, so I am not sure if there is an setting about this behaviour. If there is, then I am sorry.

**Comment by HiDeoo** [comment]
Thanks for the report.

Are we talking about his chat overlay in the video stream like we're seeing in your screenshot? If so, I don't think he's  using YaTA for this specific chat (doesn't look like it at all and if I remember correctly he's only using it on his second monitor for himself only).

Regarding the bug itself, I still tested in YaTA using your repro and it renders properly like the Twitch vanilla chat:

<img width="277" alt="Screenshot 2019-05-29 at 16 21 13" src="https://user-images.githubusercontent.com/494699/58564746-d0384a80-822d-11e9-87e4-f3236b7df417.png">

Altho, if I'm not correct, feel free to re-open.

**Comment by rhymu8354** [comment]
Thank you for the detailed report, @Neui !  @HiDeoo is correct; I don't use YaTA in my overlay.  Maybe I should?  The overlay I currently use is from StreamElements.  I may replace this with cmgriffing's "chatterlay" service when that's ready.  I'll let Chris know about this so he can test that his overlay doesn't have this issue.

**Comment by rhymu8354** [comment]
I let Chris know in his stream; not sure if he will fix it or not.

**Comment by HiDeoo** [comment]
Thanks for confirming :)

> I don't use YaTA in my overlay. Maybe I should?

It's nice to see people using YaTA altho I would admit, I'm not sure a chat overlay would be a good use case with all the UI baked into it, most of the tools would be useless in there, etc.

On the contrary, if you take a tool like the one @cmgriffing is building, it's from the ground up built properly for this usage, with overlays in mind, with tons of features dedicated to that specific usage so I think it's a no-brainer better and more qualitative choice.
