### ISSUE TITLE
Drag/drop file overlay stays

### ISSUE THREAD

**Issue by tollus** [HiDeoo/YaTA#34]
**Describe the bug**

When you drag a file across your monitor and it happens to go over the yata window sometimes it will keep the 'drop file here' overlay and not properly hide.

**To Reproduce**

Here's a clip from adam to see the repro: https://clips.twitch.tv/SteamyEndearingStarArsonNoSexy

**Expected behavior**

Expected that the overlay will go away.

**Screenshots**

Clip above

**Environment (please complete the following information)**

| Software         | Version               |
| ---------------- | --------------------- |
| YaTA             | Public (v1.11.0)           |
| Browser          | Chrome 77.0.3865.90 |
| Operating System | Windows       |

**Comment by HiDeoo** [comment]
Even after trying to drag a file more than a 100 times over the application, no matter the drag speed, I couldn't reproduce. I wonder if this could be OS-specific based on how dragging is implemented on each OS.

As a workaround, I added a close button to the drag overlay so people hitting this issue can easily close the overlay.

<img width="386" alt="Screenshot 2019-12-16 at 13 42 30" src="https://user-images.githubusercontent.com/494699/70908254-06db8400-200b-11ea-9b54-f71edcecf208.png">

**Comment by tollus** [comment]
Might've been either OS or being right on the edge on monitor 1 while dragging the file over to monitor 2. But the x definitely works, thanks!
