### ISSUE TITLE
No pages load after logging in

### ISSUE THREAD

**Issue by simoniz0r** [HiDeoo/YaTA#35]
**To Reproduce**

1. Go to yata.now.sh
2. Login to Twitch
3. Watch loading circle spin
4. Eventually end up with `Something went wrong!` error

**Error**

```
¯\_(ツ)_/¯
Something went wrong!
Try reloading the application.
```

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.11.0
| Browser          | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.99 Chrome/73.0.3683.105 Safari/537.36
| Operating System | Linux

**Comment by simoniz0r** [comment]
Apparently Twitch is having issues, so this may be a problem on Twitch's end.  I will close this if it starts working.

**Comment by HiDeoo** [comment]
Yeah, Twitch is having major issue right now due a Fornite event I think so that could be a potential cause.

**Comment by simoniz0r** [comment]
Seems to be working now.
