### ISSUE TITLE
Tiered gift subs didn't show in Yata

### ISSUE THREAD

**Issue by tollus** [HiDeoo/YaTA#36]
**Describe the bug**

When a gift sub was given in the channel, it showed the message that a gift sub was given, but didn't show the tier number for it. Is this something available in the message? Can we display that?

**To Reproduce**

1. Receive a gift sub on your channel.
2. See the message in the chat client.

**Expected behavior**

I would want it to show which Tier for the gift sub so I can properly thank,

**Screenshots**

![OrMoXVFYMx](https://user-images.githubusercontent.com/1820386/69989198-1b028a00-1511-11ea-89f9-8c49d11ac999.png)

**Environment (please complete the following information)**

| Software         | Version               |
| ---------------- | --------------------- |
| YaTA             | v1.11.0         |
| Browser          | Chrome |
| Operating System | Windows          |

**Comment by tollus** [comment]
Note, since this deals with gift subs, I don't expect you to send gift subs to test it. Let me know if there's something I can run locally to trap some sort of message when this happens so you can see details.

**Comment by HiDeoo** [comment]
I'm not sure if I'm confusing this with some other things but I remember the "tier" of something not being something I could catch without pubsub.

Anw, no matter what, I'll investigate and double check that for the next release.

**Comment by HiDeoo** [comment]
I was definitely confusing this with something else ^^ This will be fixed in the next version.

*Note: only tier 2 & 3 are indicated, I left out the word "tier" for tier 1 gifts.*
