### ISSUE TITLE
Optional support for custom channel point redemptions

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#41]
**Is your feature request related to a problem? Please describe.**

The problem I have with using YaTA while streaming with custom channel point redemptions set up is I can't see when redemptions are made in the chat.  They show up in Twitch's chat client with a purple bar on the left and a banner over the message saying what was redeemed.

In the following comparison between Twitch's chat client on the left with YaTA on the right, the first chat message was sent "normally" (not a channel points redemption) while the second chat message was sent via a channel points redemption:

![image](https://user-images.githubusercontent.com/41497796/71938073-1e69e080-3163-11ea-992d-77bf80611f38.png)

Inspecting the raw messages, note that the channel points redemption has an additional tag `custom-reward-id`.  Comparing the first message on the left with the second message on the right:

![image](https://user-images.githubusercontent.com/41497796/71938090-2b86cf80-3163-11ea-8341-cfcbd09cdb1c.png)

Also note that custom channel point redemptions *do not* appear in chat *unless* a message is included.

**Describe the solution you'd like**

Seeing as how YaTA can detect custom channel point redemptions *which include a message*, but cannot be expected to know what custom redemptions mean, the solution I would like is an optional enabling of some kind of highlighting or alerting in YaTA for custom redemptions that I have configured YaTA to understand.  Possibly a part of the "settings" where I list to YaTA custom reward IDs and corresponding banners or highlights to show in the chat.  I could go in there and say for `fda27460-ea4b-479c-ade4-791ce4494e41` to show `Custom reward 'say something as Yoda' was redeemed` in chat above the message.

**Describe alternatives you've considered**

I use this break out this window from Twitch's chat:

![image](https://user-images.githubusercontent.com/41497796/71938444-4279f180-3164-11ea-8a50-604bfaa3ddd8.png)

This displays a queue which I use to see if redemptions were made, and if so, to either `Mark as Complete` or `Reject` each one:

![image](https://user-images.githubusercontent.com/41497796/71938537-9d134d80-3164-11ea-92fc-05a322e3c403.png)

My alternative to some kind of notification in YaTA is to have to glance at this break-out window every once in a while to see if there is anything in the queue.  Even if YaTA did alert me, I would expect to have to use the break-out window anyway, since there's no API for this (as yet), however at least I would have a greater chance of knowing a redemption was made.

**Additional context**

**Comment by HiDeoo** [comment]
Thanks for your very detailed report which helped me a lot understand the situation as I was not even aware of custom rewards including a message ^^

I decided to address this with 2 changes:

- These messages are now highlighted.
- You can now open the rewards queue on your channel from the Tools menu.

<img width="226" alt="Screenshot 2020-01-08 at 15 24 22" src="https://user-images.githubusercontent.com/494699/71986954-9e5c7d00-322d-11ea-87c4-7cde9ce6dd25.png">

Regarding settings to match a reward ID to a reward name, I'd like to wait a bit and maybe let a chance for Twitch to come up with an API. They added recently a PubSub topic for rewards so maybe they'll iterate soon on it and provide proper support. Altho, if that's not the case, I think something like this could appear indeed in the streamer settings as a last resort.

Hope in the meantime, the current solution will be enough for you.
