### ISSUE TITLE
Modified emotes sent by the user don't appear as emotes

### ISSUE THREAD

**Issue by rhymu8354** [HiDeoo/YaTA#45]
**Describe the bug**

I unlocked (with channel points) a modified version of my emote today.  When I sent it with YaTA, it didn't appear as an e-mote.  However, when other people in chat posted it, it would show up as an e-mote correctly.

**To Reproduce**

1. Redeem channel points to modify one of the emotes in the channel you're reading in YaTA.
2. Type the modified emote code.

**Expected behavior**

The emote should appear in place of the modified emote code.

**Screenshots**

![image](https://user-images.githubusercontent.com/41497796/81362221-2a27ce00-9095-11ea-9ad8-5a65dbff7952.png)

Left is YaTA, right is pop-out ordinary Twitch chat.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.13.3
| Browser          | Firefox 76.0
| Operating System | Windows NT 10.0

**Comment by rhymu8354** [comment]
In the YaTA window, the emote actually showed up the second time I posted "rhymu8EJ_SO" in chat.  I believe this was because I posted it from the ordinary Twitch chat before popping it out (which resets the chat there).  So please refer only to the last two lines: next to last was from me, posted from YaTA, while last was from asquared31415; I placed YaTA and Twitch chat side-by-side to compare those two.

**Comment by HiDeoo** [comment]
Thanks for the detailed report.

This is a *"known issue"*. Currently, emotes are mostly fetched using 2 APIs:

- https://dev.twitch.tv/docs/v5/reference/chat/#get-chat-emoticons-by-set

> Gets all chat emoticons (not including their images) in one or more specified sets.

- https://dev.twitch.tv/docs/v5/reference/users/#get-user-emotes 

> Gets a list of the emojis and emoticons that the specified user can use in chat. These are both the globally available ones and the channel-specific ones (which can be accessed by any user subscribed to the channel).

*Note: the second one is already a workaround to the first one being totally buggy.*

Unfortunately, none of these endpoints will include modified emotes redeemed with channel points ¯\\_(ツ)_/¯ 

So, afaik (and would love to be wrong, feel free to re-open if that's the case), there is no way to provide this feature when sending a modified emote redeemed with channel points.
