### ISSUE TITLE
Mark Chat as read via shortcut

### ISSUE THREAD

**Issue by tamagosante** [HiDeoo/YaTA#5]
**Is your feature request related to a problem? Please describe.**
As a streamer, I want to know where the last message was that I read.

**Describe the solution you'd like**
A shortcut marking the chat until that point as read.
Maybe give a "buffer" for messages which come in when you press the shortcut. 

**Describe alternatives you've considered**
As a streamer I have multiple screens set up, so just giving focus to Yata will do the trick as well.

**Additional context**
I am not a streamer. This idea came while watching Adam's stream. I don't know if this a real issue, but in my case I already notice "Where was I again?"

**Comment by HiDeoo** [comment]
There is already a "marker" feature available in the "Tools" menu, altho it's only available using this menu manually. 

The idea of having a shortcut for it is indeed a pretty great suggestion, I'll implement that in the next version.

I'll close this issue when the change will be implemented.

**Comment by HiDeoo** [comment]
Also, if the "marker" feature is not really what you're describing, do not hesitate to tell me :)

**Comment by tamagosante** [comment]
> Also, if the "marker" feature is not really what you're describing, do not hesitate to tell me :)

It is! Nice implementation.

Glad the shortcut suggestion is new. 
I guess, you could implement even more shortcuts for other functionality as well, and in the tooltips show how icons can be accessed

**Comment by HiDeoo** [comment]
> I guess, you could implement even more shortcuts for other functionality as well, and in the tooltips show how icons can be accessed

I have plans for most common actions to be indeed binded to shortcuts (only a few are at the moment and there is not really a way to find out what shortcuts are used) and I also plan to have these shortcuts configurable through the settings, altho it's a more larger task to implement all this with a proper UI but definitely something that'll happen at some point (not even started yet).

**Comment by HiDeoo** [comment]
Shortcuts now have their own settings panel and can be customized 🎉

**Comment by tamagosante** [comment]
Looks great!

Small feedback:
<img width="484" alt="screen shot 2018-08-26 at 23 36 31" src="https://user-images.githubusercontent.com/30693990/44633253-e9ebef00-a988-11e8-96a6-066f87b22a05.png">
- On click on a shortcut, besides the visual indicator (blue outline), I expected to get some feedback that I can now edit the shortcut.
- It could be a little "dangerous" allowing to edit the shortcut by just clicking on the shortcut panel, as there is no "undo" --> dbl click?

**Comment by HiDeoo** [comment]
- Indeed, I should make it more obvious somehow, I'll think about that.
- As there is still a way to remove the shortcut if needed, I don't want to complicate the process or add a modal like some programs do (VSC for example). It's how most keybinding editors works on macOS and I've always found them simple enough.

**Comment by HiDeoo** [comment]
I added a tooltip replacing the shortcut when clicking on it indicating to the user that he just have to type the new shortcut.

Thanks for the feedback 👍

**Comment by tamagosante** [comment]
You are welcome. Good job!
