### ISSUE TITLE
Support /delete and CLEARMSG response

### ISSUE THREAD

**Issue by freaktechnik** [HiDeoo/YaTA#8]
Twitch has been rolling out a new slash command and IRC command. `/delete <message-id>` and `CLEARMSG` as a result of it. Details on what `CLEARMSG` looks like can be found at https://dev.twitch.tv/docs/irc/tags/#clearmsg-twitch-tags even though Twitch themselves don't quite fully support the command yet.

As of filing this bug Twitch only shows a Notice when the CLEARMSG comes back, but doesn't remove the message on any official client I tried.

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.5.2
| Browser          | Firefox 64.0
| Operating System | Linux

**Comment by HiDeoo** [comment]
I'll support this if this ever make it to their own official clients to ever get used. Closing this until then but added this as a todo to check regularly.

**Comment by freaktechnik** [comment]
it appears Twitch now implements this themselves.

**Comment by HiDeoo** [comment]
This is now supported and should be released soon.
