### ISSUE TITLE
Pronouns 

### ISSUE THREAD

**Issue by dpsbrdi** [HiDeoo/YaTA#85]
### Describe the solution you'd like

Hello,

would it be possible for you could add pronouns support? [https://pronouns.alejo.io/](here)

doesn't appear to be any public api documentation but chatty has some form of implementation of it if that helps [https://github.com/chatty/chatty/blob/master/src/chatty/util/Pronouns.java](chatty)

**Comment by HiDeoo** [comment]
Thanks for your suggestion.

I'm not familiar with this service, is something like this image from the [Twitch Chat pronouns Chrome extension](https://chrome.google.com/webstore/detail/twitch-chat-pronouns/agnfbjmjkdncblnkpkgoefbpogemfcii) close to something you would expect? 

![Preview](https://lh3.googleusercontent.com/Qe86CYgQ3KTQaiphcfbhQ-Uign0-KVg-E_NWzcTbtfavFe7VAnSNqFga23tjV41BP5nXZJ3cKh22N-nJ5WmpSMTS=w640-h400-e365-rj-sc0x00ffffff)

Is the Chatty implementation similar? Could you provide a screenshot of Chatty where they use this API?

Without a lot of thinking, I'm not against the idea, altho, I'm not sure I like the idea to have this in the chat directly as this would potentially means 1 extra query per message. I think a better place could be the modal when you click on a username, altho, it may not be relevant for this service? Any thoughts?

**Comment by dpsbrdi** [comment]
so chatty has 2 ways of getting the pronouns, first is when a user talks it'll go and look up there pronouns then after that every message they send will have there pronouns - although its not always reliable this way at actually getting the pronouns this way, other way for it to get the pronouns is to click on the user to bring up the user info/mod panel and it will display there pronouns in the top bar & then display it whenever they message in chat, it only checks once it then caches that users pronouns until chatty is closed so couldn't you do a similar method of caching?
![sr6db7jKWt](https://user-images.githubusercontent.com/12225926/130342851-158e78dc-bc20-4666-8b35-b9a9d86f2167.png)

**Comment by HiDeoo** [comment]
Thanks for the detailed response. The second method you mention where the data is fetched when the user details modal is opened and then cached is something doable and close to what I mentioned in my first message.

The second method they're using (fetching the data automatically when a user first talk in chat) on the other hand feels a bit much without too much thinking.

I also think a global switch to enable / disable this 3rd party integration should be added to the settings.

I added this to my todo list and I'll try to see what kind of integration we can come up with in the next version.

**Comment by musapinar** [comment]
@HiDeoo Pardon de hijacker le topic mais il me semble que vous étiez très actif sur les live de PampaTV pour DeaLimited. Je découvre que la chaîne a disparu. J'espère qu'il ne lui est arrivé rien de grave?  Est-ce qu'il s'est lassé? Je suivais occasionnellement ses diffusions et c'était encourageant de voir bosser un autoentrepreneur seul sur un si gros projet. Est-ce que ça vous ennuierai de me résumer les événements? Ca me fout un peu le cafard. Il me semble vous avoir croisé chez Adam pour BotLand également (qui n'a pas rencontré le succès escompté non plus). Désolé si je vous confonds avec quelqu'un d'autre.

**Comment by HiDeoo** [comment]
A bit late to the party, but this should be [available in the next version](https://github.com/HiDeoo/YaTA/pull/90).

As discussed, the information is visible in the chatter details modal opened when clicking a username, next to the user badges.

<img width="184" alt="Screenshot 2022-02-18 at 17 54 54" src="https://user-images.githubusercontent.com/494699/154729003-95a026e4-e755-47e9-b401-48e9cd065147.png">
