### ISSUE TITLE
Immediately show mod actions in own channel

### ISSUE THREAD

**Issue by freaktechnik** [HiDeoo/YaTA#9]
**Is your feature request related to a problem? Please describe.**

When loading YaTA for your own channel, YaTA only shows mod actions for messages once you've sent a message or the USERSTATE has come in (not sure which it is, it is just delayed for sure).

**Describe the solution you'd like**

YaTA should already know that I can execute mod actions because it's my own channel that I have loaded (as in, the channel of the currently authenticated user).

**Comment by HiDeoo** [comment]
Good catch, I remember thinking about this but I don't know if I totally forgot or something else ¯\\_(ツ)_/¯

Anw, this is now fixed.
