### ISSUE TITLE
Emotes fail loading

### ISSUE THREAD

**Issue by Durss** [HiDeoo/YaTA#91]
### Describe the bug

If you have more than 25 emote sets it crashes their loading.

### To Reproduce

Sub to enough channels so you have more than 25 emote sets.

This endpoint does not accepts more than 25 emote sets:
https://api.twitch.tv/helix/chat/emotes/set

If you need to load more than 25 sets you have to split it into multiple queries.

### Expected behavior

Emotes should load.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for spotting the issue, I just deployed a fix to address this.
