### ISSUE TITLE
Broken Display of BTTV Emotes

### ISSUE THREAD

**Issue by c17r** [HiDeoo/YaTA#93]
### Describe the bug

looks like html attributes for BTTV emotes are being shown along with the emote

### To Reproduce

Just watching a channel where someone uses BTTV emotes

### Expected behavior

To display just the emote

### Screenshots

![image](https://user-images.githubusercontent.com/148640/159009957-5a5e7149-2314-478f-bf39-56561f17d54e.png)

### How often does this bug happen?

Every time

### Browser version

Chrome 99.0.4844.51

### Operating System version

macOS Catalina 10.15.7

**Comment by HiDeoo** [comment]
Thanks for the report.

Just tried with various emotes but can't seem to repro:

<img width="442" alt="Screenshot 2022-03-18 at 14 26 41" src="https://user-images.githubusercontent.com/494699/159011259-25fff326-96b8-46e8-b418-c9c384ed3397.png">

- Do you happen to know the emote name?
- Do you know if this happen only with this one or all Bttv emotes?

**Comment by c17r** [comment]
Just got this one:
![image](https://user-images.githubusercontent.com/148640/159013683-805d00eb-e78e-4ff5-b1ac-d4954d9b4793.png)
which the mouseover hover shows as "cohhFish" so maybe custom BTTV emotes as this is on CohhCarnage's channel?

I couldn't scroll back far enough to get the one from my first report. If it comes up again during his stream (he usually does 5-7 hour blocks) I'll update here

**Comment by HiDeoo** [comment]
Thanks for the details, I think, when I have enough time to stay in his chat & see users using these emotes, I'll open a chat on his channel with a local version adding a bit more debug infos to find the issue.

**Comment by c17r** [comment]
![image](https://user-images.githubusercontent.com/148640/159015046-f619cc02-416d-4d46-8b29-55e6c50132c3.png)

Got it again, it's "cohhVIP"

**Comment by c17r** [comment]
It's annoyingly not every emote, 99% of them are fine. `FeelsBadMan` in his channel triggers it as well

![image](https://user-images.githubusercontent.com/148640/159016774-9e9cf555-5abc-430d-a0ab-cd70fb347f9e.png)

This is the last one I'll add 😄

**Comment by HiDeoo** [comment]
Random question: do you know if you reloaded the page between having the issue for the first time and now? I wonder if it could be related to an issue during the initial bttv fetches and me not handling that properly somehow.

**Comment by c17r** [comment]
Before opening the ticket and after I saw it the first time, I opened the Chrome console and did `Empty Cache and Hard Reset` but the problem persisted.

**Comment by HiDeoo** [comment]
> Before opening the ticket and after I saw it the first time, I opened the Chrome console and did `Empty Cache and Hard Reset` but the problem persisted.

Gotcha, thanks for all the details. I'll open his chat at some point and leave it opened until I can repro and see what I can find 👍🏼

**Comment by HiDeoo** [comment]
I managed to tracked down the issue. It was related to emotes registered by multiple third-party providers, for example, `POGGERS` which is registered in [BTTV](https://betterttv.com/emotes/58ae8407ff7b7276f8e594f2) & [FFZ](https://www.frankerfacez.com/emoticon/214129-POGGERS). When this happened, I was trying to replace the emote twice.

A new version with the fix has been published.

Thanks for your help.

**Comment by c17r** [comment]
Can confirm all is well now, thanks for the quick turnaround!
