### ISSUE TITLE
No Longer Seeing Controls/Settings Options

### ISSUE THREAD

**Issue by clarkio** [HiDeoo/YaTA#95]
### Describe the bug

There used to be a display at the top of the chat window that showed the options to control settings for the chat. 

### To Reproduce

1. Sign in
2. Go to a Twitch channel chat room
3. Settings are no longer visible

### Expected behavior

I would expect to see options to control font size, color, moderator options when available, etc.

### Screenshots

![image](https://user-images.githubusercontent.com/6265396/181285728-a1362140-9c9f-4b3b-b953-790d8115ece3.png)

### How often does this bug happen?

Every time

### YaTA version

Latest

### Browser version

Brave, Edge, Chrome, Firefox (all latest versions)

### Operating System version

Windows 10

**Comment by HiDeoo** [comment]
Hi @clarkio, 

There is shortcut in the application to toggle the visibility of the header bar which contains the settings button. This shortcut defaults to `Alt + t`, could you try checking if your issue could be related to this shortcut being pressed by mistake?

Thinking about it, even if it's not your issue, I think this shortcut should not be enabled if the header is visible to avoid these mistakes (as some people already reported issues about the header no longer being visible) and instead, to hide it, a button or checkbox in the settings should be used.

**Comment by clarkio** [comment]
Oh man how did I miss that?! I've been stuck without visibility to that for months 😅 I guess I accidentally hit that key combination a while back. Doing it again I can see it now. Thanks so much!

**Comment by HiDeoo** [comment]
To be honest, a "feature" hiding the main toolbar & settings that could be triggered by default with a random shortcut without any confirmation is not that good of an implementation ^^ It's on my todo list now :)

Glad we could get it fixed.

**Comment by clarkio** [comment]
Thanks for making this awesome and useful tool. It's been fantastic to use while streaming too.
